export enum STORE_ACTION_TYPE {
  AUTH = "AUTH",
  LOGOUT = "LOGOUT",
  ADD_NOTIFICATION = "ADD_NOTIFICATION",
  REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION",
  NOTES_SET = "NOTES_SET",
  NOTES_ADD = "NOTES_ADD",
  NOTES_UPDATE = "NOTES_UPDATE",
  NOTES_DELETE = "NOTES_DELETE",
  INITIALIZE = "INITIALIZE",
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
}
